# Make sure to check the documentation at http://goreleaser.com
version: 2

project_name: rankdb

env:
  - CGO_ENABLED=0
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/rankdb/main.go
    binary: rankdb
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"
  - id: rankdb-cli
    main: ./api/tool/rankdb-cli/main.go
    binary: rankdb-cli
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{ if eq .Arch \"amd64\" }}x86_64{{ else }}{{ .Arch }}{{ end }}"
    files:
      - conf/conf.stub.toml
      - api/swagger/swagger.json
      - api/swagger/swagger.yaml
      - api/public/swagger/*
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
