// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "rankdb": static TestHelpers
//
// Command:
// $ goagen
// --design=github.com/Vivino/rankdb/api/design
// --out=$(GOPATH)/src/github.com/Vivino/rankdb/api
// --version=v1.4.1

package test
