name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
          args: --new-from-rev=master --timeout=5m
          install-mode: binary
      - name: Tests
        run: |
          go mod tidy
          go test -v ./...
          go test -cpu=1 -short -race ./...
          go test -cpu=4 -short -race ./...

  go-releaser-check:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: goreleaser deprecation
        run: curl -sfL https://git.io/goreleaser | VERSION=v1.2.5 sh -s -- check

      - name: goreleaser snapshot
        run: curl -sL https://git.io/goreleaser | VERSION=v1.2.5 sh -s -- --snapshot --skip-publish --rm-dist
